# listener services that you can opt into for a repository
services:
    app.subscriber.issue_subscriber:
        class: AppBundle\Issues\IssueListener
        arguments:
            - '@app.status_api.default'

parameters:
    # defines symfony repository as default
    default_repository: symfony/symfony

    # point to the main symfony repositories
    repositories:
        symfony/symfony:
            subscribers:
                - app.subscriber.issue_subscriber
            maintainers:
                - fabpot
                - webmozart
                - Tobion
                - romainneutron
                - nicolas-grekas
                - stof
                - dunglas
                - aitboudad
                - jakzal
                - xabbuh
                - javiereguiluz
            secret: change_me
        symfony/symfony-docs:
            subscribers:
                - app.subscriber.issue_subscriber
            maintainers:
                - weaverryan
                - WouterJ
                - xabbuh
                - javiereguiluz
