# listener services that you can opt into for a repository
services:
    app.subscriber.issue_subscriber:
        class: AppBundle\Issues\IssueListener
        arguments:
            - '@app.status_api'

parameters:
    # point to the main symfony repositories
    repositories:
        symfony/symfony:
            subscribers:
                - app.subscriber.issue_subscriber
            secret: change_me
        symfony/symfony-docs:
            subscribers:
                - app.subscriber.issue_subscriber
